# Generated by Django 2.2 on 2020-05-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
        migrations.AddField(
            model_name='product',
            name='basic_camera',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='battery',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='front_camera',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='memory',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='smartphone'),
        ),
    ]
