# Generated by Django 2.2 on 2020-05-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200525_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='version',
        ),
    ]
